# Generated by Django 6.0.5 on 2026-05-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('category', models.CharField(choices=[('road', 'Yol / kaldırım'), ('water', 'Su / kanalizasyon'), ('lighting', 'Aydınlatma'), ('waste', 'Çöp / temizlik'), ('park', 'Park / yeşil alan'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Sorun türü')),
                ('photo', models.ImageField(blank=True, upload_to='complaints/', verbose_name='Fotoğraf')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Enlem')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Boylam')),
                ('reporter_name', models.CharField(blank=True, max_length=80, verbose_name='Bildiren kişi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bildirim zamanı')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Çözüldü')),
            ],
            options={
                'verbose_name': 'Şikayet',
                'verbose_name_plural': 'Şikayetler',
                'ordering': ['-created_at'],
            },
        ),
    ]
